# SLURM configuration for sim_shade_comparison

jobs:
  00_setup:
    job_name: setup_comparison
    time: "10:00"
    mem: "4G"
    cpus: 1

  01_simulation_runner:
    job_name: shade_comparison
    # ORIGINAL GRID: 1-360 (2*2*3*30 jobs)
    # EXPERIMENTAL GRID: 1-48 (2*2*2*2*1*1*3 jobs)
    array_range: 1-600
    # MCMC needs ~8-10 hours, VI needs ~30-60 min
    time: "20:00"
    mem: "8G"
    cpus: 1

  01_simulation_runner_compartments:
    job_name: compartments_comparison
    array_range: 1-120
    time: "40:00"
    mem: "8G"
    cpus: 1

  02_analyze_results:
    job_name: analyze_comparison
    time: "10:00"
    mem: "8G"
    cpus: 1

  02_analyze_compartments:
    job_name: analyze_comparison
    time: "10:00"
    mem: "8G"
    cpus: 1

  02_robustness_hardcore_power:
    job_name: robust_hc_power
    time: "4:00:00"
    mem: "16G"
    cpus: 2

  03_robustness_hardcore_null:
    job_name: robust_hc_null
    time: "5:00:00"
    mem: "16G"
    cpus: 2
